services:
  cassandra:
    image: cassandra:4.0.1
    container_name: cassandra
    hostname: cassandra
    #    mem_limit: 2g  # It's not strictly required, but it's better to have some memory limit
    healthcheck:
      test: [ "CMD", "cqlsh", "-e", "describe keyspaces" ]
      interval: 15s
      timeout: 10s
      retries: 10
    ports:
      - 9042:9042  # Expose native binary CQL port for your apps
    volumes:
      - cassandra-data:/var/lib/cassandra    # This is the volume that will persist data for cass1 node
    #      - ./etc/cass1:/etc/cassandra   # Use your own config files for full control
    environment: &environment    # Declare and save environments variables into "environment"
      - CASSANDRA_SEEDS=cassandra    # The first two nodes will be seeds
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_PASSWORD=cassandra

volumes:
  cassandra-data: